name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - web/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 20

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          cd web
          npm i
          npm run build

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: web/dist
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
